### ISSUE TITLE
Pull request for Kanban board

### ISSUE THREAD

**Issue by agneta1991** [agneta1991/recipe_app#10]
This is a two people project and the participants are:
_**Agneta Pupienyte & Toyyib Ballo**_

Link below is our projects Kanban board
https://github.com/users/agneta1991/projects/3

**Comment by julie-ify** [comment]
## Hi @agneta1991 and @Simpleshaikh1,

Good job so far!

## Highlights!
- Good task assignments ✔️
- Descriptive Issue ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
- [ ] The In Review column should come before the Done column. Kindly rearrange the columns.

  ![image](https://github.com/agneta1991/recipe_app/assets/81468675/8e922f97-10bb-4c91-acc9-f460950c5643)

- [ ] Ensure the N+1 query task is added.

  ![image](https://github.com/agneta1991/recipe_app/assets/81468675/b5446488-484f-454f-ad27-c122bd2104e7)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by agneta1991** [comment]
Added an additional issue called N+1, it has been assigned.
The columns has been swapped places and now in review is placed before done column.

**Comment by AbelG101** [comment]
![](https://media.giphy.com/media/eKfovWZOlOpbTDEX9F/giphy.gif)

# Hi @agneta1991 & @Simpleshaikh1 👋, 

**Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- Progress columns are properly ordered ✔
- N+1 task card is properly added ✔

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
